config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                           Controller#Action
#                     root GET    /                                                     kitchens#index
#     kitchen_reservations GET    /kitchens/:kitchen_id/reservations(.:format)          reservations#index
#                          POST   /kitchens/:kitchen_id/reservations(.:format)          reservations#create
#  new_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/new(.:format)      reservations#new
# edit_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id/edit(.:format) reservations#edit
#      kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#show
#                          PATCH  /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          PUT    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          DELETE /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#destroy
#                 kitchens POST   /kitchens(.:format)                                   kitchens#create
#              new_kitchen GET    /kitchens/new(.:format)                               kitchens#new
#             edit_kitchen GET    /kitchens/:id/edit(.:format)                          kitchens#edit
#                  kitchen GET    /kitchens/:id(.:format)                               kitchens#show
#                          PATCH  /kitchens/:id(.:format)                               kitchens#update
#                          PUT    /kitchens/:id(.:format)                               kitchens#update
#                          DELETE /kitchens/:id(.:format)                               kitchens#destroy
#           kitchens_users GET    /users/kitchens(.:format)                             users#kitchens
#                    users GET    /users(.:format)                                      users#index
#                          POST   /users(.:format)                                      users#create
#                 new_user GET    /users/new(.:format)                                  users#new
#                edit_user GET    /users/:id/edit(.:format)                             users#edit
#                     user GET    /users/:id(.:format)                                  users#show
#                          PATCH  /users/:id(.:format)                                  users#update
#                          PUT    /users/:id(.:format)                                  users#update
#                    login POST   /login(.:format)                                      sessions#create
#                  session GET    /session(.:format)                                    sessions#show
#                   logout GET    /logout(.:format)                                     sessions#destroy
#

require 'sidekiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  
  mount Sidekiq::Web => '/sidekiq'


  root :to => 'users#index'

  resources :kitchens do
    member do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  resources :reservations, :only => [:update, :edit]

  resources :kitchens, :except => [:index] do
    resources :reservations, :except => [:update, :edit]
    resources :photos do 
      member do
        get 'set_as_front_page_photo', :action => 'set_as_front_page_photo'
      end
    end
  end

  resources :users, :except => :destroy do
    collection do
      get 'kitchens'
    end
    collection do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  controller :sessions do
    get '/auth/facebook/callback', :action => 'create'
    get  '/session',               :action => 'show'
    get '/logout',                 :action => 'destroy',       :as => 'logout'
  end

  #omniauth-facebook routes

  get '/auth/facebook/callback',   :to => 'sessions#create'
  get '/auth/facebook',                                        :as => "facebook_login" 

  controller :static_pages do
    get '/:page_name', :action => 'show', :as => 'page'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  provider        :string(255)      not null
#  oauth_token     :string(255)      not null
#  uid             :string(255)      not null
#  name            :string(255)      not null
#  first_name      :string(255)
#  last_name       :string(255)
#  nickname        :string(255)
#  image           :string(255)
#  location        :string(255)
#  gender          :string(255)
#  verified        :boolean
#  link            :string(255)
#  timezone        :integer
#  sign_in_count   :integer          default(1), not null
#  last_sign_in_at :datetime
#  admin           :boolean          default(FALSE)
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#


class User < ActiveRecord::Base

  validates :email, :presence => true, :uniqueness => true, :length => { :minimum => 6 }, :email => true
  validates :provider, :presence => true
  validates :uid, :presence => true
  validates :name, :presence => true
  validates :oauth_token, :presence => true

  has_many :kitchens
  has_many :reservations
  has_many :active_pending_reservations, :through => :kitchens
  has_many :in_future_pending_reservations, :through => :kitchens
  

  def in_future_pending_reservations_count
    in_future_pending_reservations.count
  end

  def sign_in
    self.update_columns(:last_sign_in_at => Time.zone.now)
    self.update_columns(:sign_in_count => self.sign_in_count += 1)
  end

  def self.create_or_find_with_omniauth(auth)
    self.find_by_provider_and_uid(auth["provider"], auth["uid"]) || self.create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.email = auth['info']['email']
      user.provider = auth['provider']
      user.oauth_token = auth['credentials']['token']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.first_name = auth['info']['first_name']
      user.last_name = auth['info']['last_name']
      user.nickname = auth['info']['nickname']
      user.image = auth['info']['image']
      user.location = auth['info']['location']
      user.gender = auth['extra']['raw_info']['gender']
      user.verified = auth['info']['verified']
      user.link = auth['extra']['raw_info']['link']
      user.timezone = auth['extra']['raw_info']['timezone']
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authorization!, :only => [:kitchens, :reservations_all, :reservations_pending, :reservations_approved,
                :reservations_denied]
  def index
    if logged_in?
      redirect_to kitchens_path
    else
      render :index
    end
  end

  def kitchens
    @kitchens = Kitchen.for_user(current_user).active
    if @kitchens.empty?
      render :no_kitchen_page
    else
      render :user_created_kitchens
    end
  end

  def reservations_all
    @reservations = Reservation.for_user(current_user)
    @reservations_pending = current_user.reservations.pending.select { |reservation| reservation.in_future? }
    @reservations_approved = current_user.reservations.approved.active
    @reservations_denied = current_user.reservations.denied
    render :user_reservations_all
  end

  def reservations_pending
    @reservations = current_user.reservations.pending.order("reserve_date DESC, reserve_time DESC")
    render :user_reservations_pending
  end

  def reservations_approved
    @reservations = current_user.reservations.approved.order("reserve_date DESC, reserve_time DESC")
    render :user_reservations_approved
  end

  def reservations_denied
    @reservations = current_user.reservations.denied.order("reserve_date DESC, reserve_time DESC")
    render :user_reservations_denied
  end

  def new
    @user = User.new
  end

  private

  def require_authorization!
    redirect_to root_path unless logged_in?
  end

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_photo_url(user, params = {})
    uri = Addressable::URI.parse(user.image)
    uri.query = params.to_param
    uri.to_s
  end

  def user_photo_tag(user, params = {})
    image_tag(user_photo_url(user, params))
  end
end

app/views/users/_sign_up_form.html.erb
<div>
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(user.errors.count, "error") %>Please check your input for the following guideline</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <h4><%= f.label :email %></h4>
    <%= f.text_field :email, :placeholder => "Email", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :nickname %></h4>
    <%= f.text_field :nickname, :placeholder => "Nickname", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :password  %></h4>
    <%= f.password_field :password, :placeholder => "Password", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :password_confirmation %></h4>
    <%= f.password_field :password_confirmation, :placeholder => "Password", :class => "input_box_normal" %>
  </div>

  <div class="actions">
    <%= f.submit "Create Account", :class => "button_normal" %>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<div id="home_page">
  <div class="welcome_message">
    <h1>Welcome to Couchfoodie</h1>
    <p>A place to share your cookings, with someone that would appreciate them.</p>
    <p><button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_large">
      Join Us
    </button></p>
  </div>
  <div class="message_for_host content">
    <h2>Do you enjoy cooking?</h2>
    <p>Create a Home Kitchen; tell people where you are, what you typically cook and when is convenient. Welcome neighbors and guests that would appreciate your food and make some new friends. In return, your guests will express gratitude in their own way! </p>
    <p><button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_large">
        Get Started
      </button></p>
  </div>
  <div class="message_for_guest content">
    <h2>Are you hungry?</h2>
    <p>You'd like to eat healthy but stressed out about cooking? Maybe it isn't so much a problem for your neighbor. See if there are any Home Kitchens around you that are willing to share their food. Remember, hosts invite you out of their kindness. Make sure to show your appreciation in some way; at the minimum, make a donation that covers the cost of ingredient.</p>
    <p><button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_large">
      Find Kitchens
    </button></p>
  </div>
</div>

app/views/users/new.html.erb
<div class="registration">

  <div class="registration_form">
    <h1>Register</h1>
    <%= render partial: "sign_up_form", :locals => { :user => @user } %>
  </div>

</div>

app/views/users/no_kitchen_page.erb
<div class="my_kitchen_list">

  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <div class="title">
    <h2>My Kitchens</h2>
  </div>

  <div class="no_kitchen_message">
    <p>You have no kitchen yet! Get started by <%= link_to "Create Kitchen", new_kitchen_path %></p>
  </div>
  
</div>

app/views/users/no_kitchen_page.html.erb
<div class="my_kitchen_list">

  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <div class="title">
    <h2>My Kitchens</h2>
  </div>

  <div class="no_kitchen_message">
    <p>You have no kitchen yet! Get started by <%= link_to "Create Kitchen", new_kitchen_path %></p>
  </div>
  
</div>

app/views/users/user_created_kitchen.erb
<h1 class="header"><%= render partial: "shared/header_logged_in" %></h1>
<br>

<div class="notice">
  <% if flash[:notice] %>
    <strong><%= flash[:notice] %></strong>
  <% end %>
</div>

<% @kitchens.each do |kitchen| %>
<hr>
  <h3><%= kitchen.name %></h3><br>
  <strong>Kitchen owner: </strong> <%= kitchen.user.nickname %><br>
  <strong>Description: </strong><%= kitchen.description %><br>
  <strong>Location: </strong> <%= kitchen.city %>, <%= kitchen.state %>, <%= kitchen.zipcode %><br>
  <%= button_to("Edit", edit_kitchen_path(kitchen), :method => :get, :class => "post_button")%><br>
  <%= button_to("Delete", kitchen_path(kitchen), :method => :delete, :class => "post_button")%><br>
<hr>
<% end %>

app/views/users/user_created_kitchens.erb
<div class="my_kitchen_list">

  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>
  
  <ul class="my_kitchen clearfix ">
    <% @kitchens.each do |kitchen| %>
    <li>
      <div class="single_kitchen clearfix">
        <dl class="single_kitchen_info clearfix">
          <dt class="kitchen_name"><%= kitchen.name %></dt>
          <dt class="title">Description: </dt>
          <dd><%= kitchen.description %></dd>
          <dt class="title">Location: </dt> 
          <dd><%= kitchen_location(kitchen) %></dd>
        </dl>

        <div class="kitchen_reservations_in_kitchen_block clearfix">
          <ul class="clearfix">
            <li><%= link_to "Pending reservations (#{kitchen.reservations.pending.count})", reservations_pending_kitchen_path(kitchen) %></li>
            <li><%= link_to "Approved reservations (#{kitchen.reservations.approved.count})", reservations_approved_kitchen_path(kitchen) %></li>
            <li> <%= link_to "Denied reservations (#{kitchen.reservations.denied.count})", reservations_denied_kitchen_path(kitchen)%></li>
          </ul>
        </div>
        <div class="kitchen_buttons">
          <ul>
            <li><%= button_to("Add photo", new_kitchen_photo_path(kitchen), :method => :get, :class => "button_normal")%></li>
            <li><%= button_to("Edit", edit_kitchen_path(kitchen), :method => :get, :class => "button_normal")%></li>
            <li><%= button_to("Delete", kitchen_path(kitchen), :method => :delete, :class => "button_normal")%></li>
          </ul>
        </div>
        <ul class="photo-list">
          <% if kitchen.photos.empty? %>
            <h3>No photos. :(</h3>
          <% else %>
            <% kitchen.photos.each do |photo| %>
              <li><%= image_tag(photo.picture.gallery_fill.url) %></li>
            <% end %>
          <% end %>
        </ul>
      </div> 
    </li>
  <% end %>
  </ul>
</div>

app/views/users/user_created_kitchens.html.erb
<div class="my_kitchen_list">

  <div class="title">
    <h2>My Kitchens</h2>
  </div>
  
  <ul class="my_kitchens clearfix ">
    <% @kitchens.each do |kitchen| %>
    <li>
      <% if kitchen.front_page_photo %>
        <div class="single_kitchen clearfix">
          <ul class="single_kitchen_info clearfix">
            <li class="kitchen_name"><%= link_to kitchen.name, kitchen_path(kitchen) %></li>
            <li class="menu"><%= kitchen.menu %></li>
          </ul>
          <div class="thumbnail_container">
            <%= link_to image_tag(kitchen.show_front_page_photo_thumbnail), kitchen_path(kitchen), :class => 'darken' %>
          </div>
          <div class="kitchen_reservations_in_kitchen_block clearfix">
            <ul class="clearfix">
              <li><%= link_to "Pending reservations (#{kitchen.reservations.pending.in_future.count} waiting reply)", reservations_pending_kitchen_path(kitchen) %></li>
              <li><%= link_to "Approved reservations (#{kitchen.reservations.approved.active.count} active)", reservations_approved_kitchen_path(kitchen) %></li>
              <li> <%= link_to "Denied reservations (#{kitchen.reservations.denied.count} total)", reservations_denied_kitchen_path(kitchen)%></li>
            </ul>
          </div>
          <div class="kitchen_buttons">
            <ul>
              <li><%= button_to("Add photo", new_kitchen_photo_path(kitchen), :method => :get, :class => "button_normal")%></li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="single_kitchen clearfix">
          <ul class="single_kitchen_info clearfix">
            <li class="kitchen_name"><%= kitchen.name %></li>
            <li class="message">Your kitchen is incomplete, add cover photo or continue editing</li>
          </ul>
          <div class="thumbnail_container thumbnail_placeholder">
            <ul class="buttons">
              <li><%= button_to("Add cover photo", new_kitchen_photo_path(kitchen), :method => :get, :class => "button_normal")%></li>
              <li>
                <%= button_to("Edit", edit_kitchen_path(kitchen), :method => :get, :class => "button_normal")%>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/users/user_reservations_all.erb
<div class="user_reservations_all">
  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>
  
  <div class="reservation_all">
    <ul>
      <li><%= link_to "Waiting for kitchen reply (#{@reservations_pending.count})", reservations_pending_users_path %></li>
      <li><%= link_to "Approved by kitchen (#{@reservations_approved.count})", reservations_approved_users_path %></li>
      <li><%= link_to "Denied by kitchen (#{@reservations_denied.count})", reservations_denied_users_path %></li>
    </ul>
  </div>
</div>

app/views/users/user_reservations_all.html.erb
<div class="user_reservations_all_page">
  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <div class="title">
    <h2>My Reservations</h2>
  </div>
  
  <div class="reservation_all">
    <ul>
      <li><%= link_to "Waiting for kitchen reply (#{@reservations_pending.count} in future)", reservations_pending_users_path %></li>
      <li><%= link_to "Approved by kitchen (#{@reservations_approved.count} active)", reservations_approved_users_path %></li>
      <li><%= link_to "Denied by kitchen (#{@reservations_denied.count} total)", reservations_denied_users_path %></li>
    </ul>
  </div>
</div>

app/views/users/user_reservations_approved.erb
<div class="reservations_list clearfix">
  <div class="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <% if @reservations.empty? %>
    <h2>There is nothing here.<h2>
  <% end %>

  <h2>Reservations approved by kitchen</h2>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
  <li>
    <div class="single_reservation clearfix">
        <dl class="single_reservation_info">
          <dt class="title">Status:</dt>
          <dd><%= reservation.status %></dd>
          <dt class="title">Reservation for:</dd>
          <dd><%= reservation.kitchen.name %></dd>
          <dt class="title">Number of people:</dt>
          <dd><%= reservation.guest_number %></dd>
          <dt class="title">Reserve on:</dt>
          <dd><%= show_reservation_time(reservation) %></dd>
          <dt class="title">Location:</dt>
          <dd><%= kitchen_location(reservation.kitchen) %></dd>
          <dt class="title">My reservation message:</dt>
          <dd><%= reservation.message_from_guest %></dd>
          <dt class="title">Message from <%= reservation.kitchen.name %>:</dt>
          <dd><%= reservation.message_from_host %></dd>
        </dl>
    </div>
  </li>
  <% end %>
  </ul>
</div>

app/views/users/user_reservations_denied.html.erb
<div class="reservations_list clearfix">

  <div class="title">
    <h2>Denied reservations</h2>
    <% if @reservations.empty? %>
      <h2>There is nothing here.</h2>
    <% end %>
  </div>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <ul class="description_list">
            <li class="title">Status: <%= reservation.status %></li>
            <li><%= show_reservation_time(reservation) %></li>
            <li>
              <div class="kitchen_info">
                <div class="kitchen_link clearfix">
                  <span class="kitchen_name"><%= link_to "#{reservation.kitchen.name}", kitchen_path(reservation.kitchen) %></span> - For <%= reservation.guest_number %> Guest(s)
                </div> 
                <div class="images">
                  <span class="kitchen_image"><%= link_to image_tag(reservation.kitchen.show_front_page_photo_thumbnail), kitchen_path(reservation.kitchen) %></span><span class="kitchen_user_image"><%= link_to user_photo_tag(reservation.kitchen.user, :type => "square", :height => 100, :width => 100), reservation.kitchen.user.link, :target => "_blank" %></span>
                </div>
              </div>
            </li>
            <li>
              <%= render :partial => "kitchens/kitchen_address_no_street", :locals => { :kitchen => reservation.kitchen } %>
            </li>
            <li class="title">Message from <%= reservation.kitchen.user.first_name %></li>
            <li><%= reservation.message_from_host %></li>
            <li class="title">My original reservation message</li>
            <li><%= reservation.message_from_guest %></li>
          </ul>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/users/user_reservations_pending.erb
<div class="reservations_list clearfix">
  <div class="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <% if @reservations.empty? %>
    <h2>There is nothing here.</h2>
  <% end %>

  <h2>Reservations waiting for kitchen approval</h2>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <dl class="single_reservation_info">
            <dt class="title">Status:</dt>
            <dd><%= reservation.status %></dd>
            <dt class="title">Reservation for:</dt>
            <dd><%= reservation.kitchen.name %></dd>
            <dt class="title">Number of people:</dt>
            <dd><%= reservation.guest_number %></dd>
            <dt class="title">Reserve on:</dt>
            <dd><%= show_reservation_time(reservation) %></dd>
            <dt class="title">Location:</dt>
            <dd><%= kitchen_location_no_street(reservation.kitchen) %></dd>
            <dt class="title">My reservation message</dt>
            <dd><%= reservation.message_from_guest %></dd>
          </dl>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/users/user_reservations_pending.html.erb
<div class="reservations_list clearfix">

  <div class="title">
    <h2>Pending reservations</h2>
    <% if @reservations.empty? %>
      <h2>There is nothing here.</h2>
    <% end %>
  </div>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <ul class="description_list">
            <li class="title">Status: <%= reservation.status %></li>
            <li><%= show_reservation_time(reservation) %></li>
            <li>
              <div class="kitchen_info">
                <div class="kitchen_link clearfix">
                  <span class="kitchen_name"><%= link_to "#{reservation.kitchen.name}", kitchen_path(reservation.kitchen) %></span> - For <%= reservation.guest_number %> Guest(s)
                </div> 
                <div class="images">
                  <span class="kitchen_image"><%= link_to image_tag(reservation.kitchen.show_front_page_photo_thumbnail), kitchen_path(reservation.kitchen) %></span><span class="kitchen_user_image"><%= link_to user_photo_tag(reservation.kitchen.user, :type => "square", :height => 100, :width => 100), reservation.kitchen.user.link, :target => "_blank" %></span>
                </div>
              </div>
            </li>
            <li>
              <%= render :partial => "kitchens/kitchen_address_no_street", :locals => { :kitchen => reservation.kitchen } %>
            </li>
            <li class="title">My original reservation message</li>
            <li><%= reservation.message_from_guest %></li>
          </ul>
      </div>
    </li>
  <% end %>
  </ul>
</div>