config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                           Controller#Action
#                     root GET    /                                                     kitchens#index
#     kitchen_reservations GET    /kitchens/:kitchen_id/reservations(.:format)          reservations#index
#                          POST   /kitchens/:kitchen_id/reservations(.:format)          reservations#create
#  new_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/new(.:format)      reservations#new
# edit_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id/edit(.:format) reservations#edit
#      kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#show
#                          PATCH  /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          PUT    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          DELETE /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#destroy
#                 kitchens POST   /kitchens(.:format)                                   kitchens#create
#              new_kitchen GET    /kitchens/new(.:format)                               kitchens#new
#             edit_kitchen GET    /kitchens/:id/edit(.:format)                          kitchens#edit
#                  kitchen GET    /kitchens/:id(.:format)                               kitchens#show
#                          PATCH  /kitchens/:id(.:format)                               kitchens#update
#                          PUT    /kitchens/:id(.:format)                               kitchens#update
#                          DELETE /kitchens/:id(.:format)                               kitchens#destroy
#           kitchens_users GET    /users/kitchens(.:format)                             users#kitchens
#                    users GET    /users(.:format)                                      users#index
#                          POST   /users(.:format)                                      users#create
#                 new_user GET    /users/new(.:format)                                  users#new
#                edit_user GET    /users/:id/edit(.:format)                             users#edit
#                     user GET    /users/:id(.:format)                                  users#show
#                          PATCH  /users/:id(.:format)                                  users#update
#                          PUT    /users/:id(.:format)                                  users#update
#                    login POST   /login(.:format)                                      sessions#create
#                  session GET    /session(.:format)                                    sessions#show
#                   logout GET    /logout(.:format)                                     sessions#destroy
#

require 'sidekiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  
  mount Sidekiq::Web => '/sidekiq'


  root :to => 'users#index'

  resources :kitchens do
    member do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  resources :reservations, :only => [:update, :edit]

  resources :kitchens, :except => [:index] do
    resources :reservations, :except => [:update, :edit]
    resources :photos do 
      member do
        get 'set_as_front_page_photo', :action => 'set_as_front_page_photo'
      end
    end
  end

  resources :users, :except => :destroy do
    collection do
      get 'kitchens'
    end
    collection do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  controller :sessions do
    get '/auth/facebook/callback', :action => 'create'
    get  '/session',               :action => 'show'
    get '/logout',                 :action => 'destroy',       :as => 'logout'
  end

  #omniauth-facebook routes

  get '/auth/facebook/callback',   :to => 'sessions#create'
  get '/auth/facebook',                                        :as => "facebook_login" 

  controller :static_pages do
    get '/:page_name', :action => 'show', :as => 'page'
  end

end

app/views/shared/_footer.html.erb
<footer>
  <h4>Copyright &copy; 2014 Couchfoodie</h4>
  <h4><%= link_to "About", page_path('about') %></h4>
</footer>

app/views/shared/_header_all.html.erb
<% if current_user %> 
  <div id="logged_in_header">
    <div class="home_link">
      <%= link_to 'Couchfoodie', root_url %> <span class="beta">BETA</span>
    </div>
    <nav>
      <ul id="logged_in_nav_list">
        <li class="drop_down_trigger user_image_circle_container header_menu"><%= user_photo_tag(current_user, :type => "square", :height => 100, :width => 100)%><span class="user_first_name"><%= current_user.first_name %></span><i class="fa fa-caret-down"></i>
          <ul class="drop_down_list">
            <li><%= link_to "My reservations (#{current_user.reservations.approved.active.count} approved active)", reservations_all_users_path %></li>
            <li><%= link_to "My Kitchens (#{current_user.in_future_pending_reservations_count} waiting reply)", kitchens_users_path %></li>
            <li><%= link_to('Logout', logout_path) %></li>
          </ul>
        </li>
        <li class="create_kitchen header_menu"><%= link_to "Create Kitchen", new_kitchen_path %></li>
      </ul>
    </nav>
  </div>
  
<% else %>
  <div id="logged_out_header">
    <nav><%= render :partial => "shared/index_page_modal" %></nav>
  </div>
<% end %>

app/views/shared/_header_not_logged_in.html.erb
<h1 class="welcome"> Welcome to Couchfoodie, everyone is a chef and foodie! <%= link_to 'Home', root_url %> </h1>

app/views/shared/_index_page_modal.html.erb
<div id="front_page_modal">

  <!-- Button trigger modal -->
  <ul class="modal-button-list">
    <li id="site_name">
      <%= link_to 'Couchfoodie', root_url %> <span class="beta">BETA</span>
    </li>
    <li>
      <button data-my-modal="#user_modal" data-toggle="modal" class="button_small" id="login_button">
        Log in
      </button>
    </li>
    <li>
      <button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_small" id="sign_up_button">
        Sign Up
      </button>
    </li>
  </ul>

   <!-- modal content -->

  <div class="my-modal" id="sign_up_modal">
    <div class="modal-container">
      <div class="my-modal-background">
      </div>
      <div class="my-modal-content">
        <a class="fb_button" href="<%= facebook_login_path %>">
          <i class="fa fa-facebook fa-2x">
            <span class="text_container">Sign up with Facebook</span>
          </i>
        </a>
      </div>
    </div>
  </div>

  <div class="my-modal" id="user_modal">
    <div class="modal-container">
      <div class="my-modal-background">
      </div>
      <div class="my-modal-content">
        <a class="fb_button" href="<%= facebook_login_path %>">
          <i class="fa fa-facebook fa-2x">
            <span class="text_container">Log in with Facebook</span>
          </i>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login_form.html.erb
<%= form_for(:session, :url => login_path, :method => :post) do |f| %>
  <table class="sign_in_table", cellspacing="20">
    <tr>
      <td align="left"><span class="login_table_content">Email</span></td> 
      <td><%= f.text_field(:email, :placeholder => "Email", :class => "input_box_normal")%></td>
    </tr>
    <tr>
      <td align="left"><span class="login_table_content">Password</span></td>
      <td><%= f.password_field(:password, :placeholder => "Password", :class => "input_box_normal")%></td>
    </tr>
  </table><br>
    <%= f.submit "Login", :class => "button_normal" %>
<% end %>

app/views/shared/_modal.html.erb
  <div id="front_page_modal">
    <div id="content">

      <!-- Button trigger modal -->
      <ul class="modal-button-list">
        <li>
          <button data-my-modal="#user_modal" data-toggle="modal" class="button_normal">
            Log in
          </button>
        </li>
        <li>
          <button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_normal">
            Sign Up
          </button>
        </li>
      </ul>

      <div class="my-modal" id="sign_up_modal">
        <div class="cool-container">
          <div class="my-modal-background"></div>
          <div class="my-modal-content">
            <a href="#" class="my-modal-close">[X]</a>
            <h2>Sign Up modal</h2>
            <%= render :partial => "users/sign_up_form", :locals => { :user => User.new } %>
          </div>
        </div>
      </div>

      <div class="my-modal" id="user_modal">
        <div class="cool-container">
          <div class="my-modal-background"></div>
          <div class="my-modal-content">
            <a href="#" class="my-modal-close">[X]</a>
            <h2>Sign In modal</h2>
            <%= render :partial => "shared/login_form", :locals => { :user => User.new } %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_photo_upload_modal.html.erb
<div id="photo_upload_modal">
  <div class="waiting_modal" id="photo_modal">
    <div class="modal-container">
      <div class="waiting_modal_background">
      </div>
      <div class="waiting_modal_content">
        We are uploading your photo, you will be redirected shortly. Thanks for your patience!
      </div>
    </div>
  </div>
</div>