config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                           Controller#Action
#                     root GET    /                                                     kitchens#index
#     kitchen_reservations GET    /kitchens/:kitchen_id/reservations(.:format)          reservations#index
#                          POST   /kitchens/:kitchen_id/reservations(.:format)          reservations#create
#  new_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/new(.:format)      reservations#new
# edit_kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id/edit(.:format) reservations#edit
#      kitchen_reservation GET    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#show
#                          PATCH  /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          PUT    /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#update
#                          DELETE /kitchens/:kitchen_id/reservations/:id(.:format)      reservations#destroy
#                 kitchens POST   /kitchens(.:format)                                   kitchens#create
#              new_kitchen GET    /kitchens/new(.:format)                               kitchens#new
#             edit_kitchen GET    /kitchens/:id/edit(.:format)                          kitchens#edit
#                  kitchen GET    /kitchens/:id(.:format)                               kitchens#show
#                          PATCH  /kitchens/:id(.:format)                               kitchens#update
#                          PUT    /kitchens/:id(.:format)                               kitchens#update
#                          DELETE /kitchens/:id(.:format)                               kitchens#destroy
#           kitchens_users GET    /users/kitchens(.:format)                             users#kitchens
#                    users GET    /users(.:format)                                      users#index
#                          POST   /users(.:format)                                      users#create
#                 new_user GET    /users/new(.:format)                                  users#new
#                edit_user GET    /users/:id/edit(.:format)                             users#edit
#                     user GET    /users/:id(.:format)                                  users#show
#                          PATCH  /users/:id(.:format)                                  users#update
#                          PUT    /users/:id(.:format)                                  users#update
#                    login POST   /login(.:format)                                      sessions#create
#                  session GET    /session(.:format)                                    sessions#show
#                   logout GET    /logout(.:format)                                     sessions#destroy
#

require 'sidekiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end
  
  mount Sidekiq::Web => '/sidekiq'


  root :to => 'users#index'

  resources :kitchens do
    member do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  resources :reservations, :only => [:update, :edit]

  resources :kitchens, :except => [:index] do
    resources :reservations, :except => [:update, :edit]
    resources :photos do 
      member do
        get 'set_as_front_page_photo', :action => 'set_as_front_page_photo'
      end
    end
  end

  resources :users, :except => :destroy do
    collection do
      get 'kitchens'
    end
    collection do
      get 'reservations_all'
      get 'reservations_pending'
      get 'reservations_approved'
      get 'reservations_denied'
    end
  end

  controller :sessions do
    get '/auth/facebook/callback', :action => 'create'
    get  '/session',               :action => 'show'
    get '/logout',                 :action => 'destroy',       :as => 'logout'
  end

  #omniauth-facebook routes

  get '/auth/facebook/callback',   :to => 'sessions#create'
  get '/auth/facebook',                                        :as => "facebook_login" 

  controller :static_pages do
    get '/:page_name', :action => 'show', :as => 'page'
  end

end

app/models/kitchen.rb
# == Schema Information
#
# Table name: kitchens
#
#  id                  :integer          not null, primary key
#  name                :string(255)      not null
#  description         :text
#  street_address      :string(255)      not null
#  city                :string(255)      not null
#  state               :string(255)      not null
#  zipcode             :string(255)      not null
#  latitude            :float
#  longtitude          :float
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer          not null
#  data_status         :string(255)      default("active"), not null
#  front_page_photo_id :integer
#  menu                :string(255)      not null
#
# Indexes
#
#  index_kitchens_on_front_page_photo_id  (front_page_photo_id)
#  index_kitchens_on_user_id              (user_id)
#


class Kitchen < ActiveRecord::Base

  # VALID_STATES = %w(AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO
  #                   MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV MI WY
  #                   AS DC FM GU MH MP PW PR VI AE AA AP).sort
  # This list contains abbreviation for 50 States in US + 9 commonwealth/territory + 3 Military State
  
  VALID_STATES = %w(CA)

  VALID_CITIES = ["Alameda", "Albany", "American Canyon", "Antioch", "Belmont", "Belvedere", "Benicia", "Berkeley",
  "Brentwood", "Brisbane", "Burlingame", "Calistoga", "Campbell", "Clayton", "Cloverdale", "Concord",
  "Cotati", "Cupertino", "Daly City", "Dixon", "Dublin", "East Palo Alto", "El Cerrito", "Emeryville",
  "Fairfield", "Foster City", "Fremont", "Gilroy", "Half Moon Bay", "Hayward", "Healdsburg", "Hercules",
  "Lafayette", "Larkspur", "Livermore", "Los Altos", "Martinez", "Menlo Park", "Mill Valley", "Millbrae",
  "Milpitas", "Monte Sereno", "Morgan Hill", "Mountain View", "Napa", "Newark", "Novato", "Oakland",
  "Oakley", "Orinda", "Pacifica", "Palo Alto", "Petaluma", "Piedmont", "Pinole", "Pittsburg", "Pleasant Hill",
  "Pleasanton", "Redwood City", "Richmond", "Rio Vista", "Rohnert Park", "San Bruno", "San Carlos",
  "San Francisco", "San Jose", "San Leandro", "San Mateo", "San Pablo", "San Rafael", "San Ramon",
  "Santa Clara", "Santa Rosa", "Saratoga", "Sausalito", "Sebastopol", "Sonoma", "South San Francisco",
  "St. Helena", "Suisun City", "Sunnyvale", "Union City", "Vacaville", "Vallejo", "Walnut Creek",
  "Atherton", "Colma", "Corte Madera", "Danville", "Fairfax", "Hillsborough", "Los Altos Hills",
  "Los Gatos", "Moraga", "Portola Valley", "Ross", "San Anselmo", "Tiburon", "Windsor", "Woodside",
  "Yountvill"].sort

  scope :for_user, lambda { |user| where(:user => user) }
  scope :active, lambda { where(:data_status => "active") }
  scope :with_photo, lambda { where.not(:front_page_photo => nil) }
  scope :published, lambda { active.with_photo }

  validates :name, :presence => true, :uniqueness => true, :length => { :minimum => 6 , :maximum => 50 }
  validates :menu, :presence => true, :length => { :in => (5..250)  }
  validates :description, :length => { :maximum => 350  }
  validates :street_address, :presence => true, :length => { :minimum => 6, :maximum => 50 }
  validates :city, :presence => true, :inclusion => { :in => VALID_CITIES }
  validates :state, :presence => true, :length => { :is => 2 },
            :inclusion => { :in => VALID_STATES }
  validates :zipcode, :presence => true, :length => { :minimum => 5 },
            :format => { :with => /\A\d{5}(-\d{4})?\z/, message: "should be in the form 91234 or 91234-6789"}
  validates :data_status, :presence => true, :inclusion => { :in => ["active", "archive"] }

  validates :user, :presence => true

  belongs_to :user
  belongs_to :front_page_photo, :class_name => "Photo"
  has_many :reservations
  has_many :photos
  has_many :active_pending_reservations, 
           lambda { Reservation.pending.active },
           :class_name => 'Reservation'
  has_many :in_future_pending_reservations,
           lambda { Reservation.pending.in_future },
           :class_name => 'Reservation'
  has_many :processed_photos,
           lambda { processed },
           :class_name => "Photo"
  has_many :unprocessed_photos,
           lambda { unprocessed },
           :class_name => "Photo"

  def editable_by?(user)
    self.editable? && user.present? && self.user == user
  end

  def editable?
    self.data_status == "active"
  end

  def archive!
    self.update_attributes(:data_status => "archive")
  end

  def archived?
    self.data_status == 'archive'
  end

  def set_front_page_photo(photo)
    self.front_page_photo = photo
    self.save!
  end

  def show_front_page_photo_thumbnail
    if self.front_page_photo
      self.front_page_photo.picture.gallery_fill_thumbnail.url
    end
  end

  def show_cover_photo
    if self.front_page_photo
      self.front_page_photo.picture.gallery_fill_cover.url
    end
  end

end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, :only => [:show, :edit, :update, :destroy, :reservations_pending,
                :reservations_approved, :reservations_denied]
  before_action :require_authorization!, :only => [:edit, :update, :destroy, :reservations_pending,
                :reservations_approved, :reservations_denied]
  before_action :require_login

  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchen = Kitchen.new
    @reservation = Reservation.new
    @kitchens = Kitchen.published.order("created_at ASC")
    render :index
  end

  def reservations_pending
    @kitchen = Kitchen.find(params[:id])
    @reservations = @kitchen.reservations.pending.order("reserve_date DESC, reserve_time DESC")
    @future_reservations = @kitchen.reservations.pending.select { |reservation| reservation.in_future? }
    render :kitchen_reservations_pending
  end

  def reservations_approved
    @kitchen = Kitchen.find(params[:id])
    @reservations = @kitchen.reservations.approved.order("reserve_date DESC, reserve_time DESC")
    render :kitchen_reservations_approved
  end

  def reservations_denied
    @kitchen = Kitchen.find(params[:id])
    @reservations = @kitchen.reservations.denied.order("reserve_date DESC, reserve_time DESC")
    render :kitchen_reservations_denied
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
    @processed_photos = @kitchen.processed_photos.order("created_at ASC")
    @unprocessed_photos = @kitchen.unprocessed_photos.order("created_at ASC")
    render :show
  end

  # GET /kitchens/new
  def new
    @kitchen = Kitchen.new
  end

  # GET /kitchens/1/edit
  def edit
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(kitchen_params)
    @kitchen.user = current_user

    if @kitchen.save
      redirect_to new_kitchen_photo_path(@kitchen)
    else
      render :new
    end
  end

  # PATCH/PUT /kitchens/1
  # PATCH/PUT /kitchens/1.json
  def update
    if @kitchen.update(kitchen_params)
      redirect_to kitchens_users_path, notice: 'Kitchen was succesfully updated'
    else
      render :edit
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    @kitchen.archive!
    @kitchen.reservations.each { |reservation| reservation.archive! }
    redirect_to kitchens_users_path, notice: 'Kitchen was succesfully deleted'
  end

  private

  def require_authorization!
    redirect_to root_path unless @kitchen.editable_by?(current_user)
  end

  def require_login
    redirect_to root_path unless logged_in?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_kitchen
    @kitchen = Kitchen.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kitchen_params
    params.require(:kitchen).permit(:name, :menu, :description, :street_address, :city,
                   :state, :zipcode, :data_status)
  end

  def kitchen_selection
    params.permit(:id)
  end
end

app/helpers/kitchens_helper.rb
module KitchensHelper
  def kitchen_location(kitchen)
    "%s, %s, %s, %s" % [kitchen.street_address, kitchen.city, kitchen.state, kitchen.zipcode]
  end

  def kitchen_location_no_street(kitchen)
    "%s, %s, %s" % [kitchen.city, kitchen.state, kitchen.zipcode]
  end
end

app/views/kitchens/_approve_reservation_form.html.erb
<%= form_for reservation do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(reservation.errors.count, "error") %>Please check your input for the following guideline</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Send a warm welcome message" %><br>
    <%= f.text_area :message_from_host, :class => "text_box" %>
  </div>

  <div class="field">
    <%= f.hidden_field :status, :value => "approved" %>
  </div>

  <div class="actions">
    <%= f.submit "Approve", :class => "button_normal" %>
  </div>
<% end %>

app/views/kitchens/_deny_reservation_form.html.erb
<%= form_for reservation do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(reservation.errors.count, "error") %>Please check your input for the following guideline</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Maybe you can't accomodate, how about a brief explaination?" %><br>
    <%= f.text_area :message_from_host, :class => "text_box" %>
  </div>

  <div class="field">
    <%= f.hidden_field :status, :value => "denied" %>
  </div>

  <div class="actions">
    <%= f.submit "Deny", :class => "button_normal" %>
  </div>
<% end %>

app/views/kitchens/_kitchen_address_no_street.html.erb
<div itemscope itemtype="http://schema.org/Person">
  <div class="address" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span class="city" itemprop="addressLocality">
      <%= kitchen.city %>
    </span>
    <span class="state" itemprop="addressRegion">
      <%= kitchen.state %>
    </span>
    <span class="zipcode" itemprop="postalCode">
      <%= kitchen.zipcode %>
    </span>
  </div>
</div>

app/views/kitchens/_kitchen_list.html.erb
<ul class="kitchen_index_list clearfix">
  <% kitchens.each do |kitchen| %>
    <li class="kitchen_container clearfix">
      <div class="thumbnail_container">
        <%= link_to image_tag(kitchen.show_front_page_photo_thumbnail), kitchen_path(kitchen), :class => "darken" %>
      </div>

      <div class="kitchen_info">
        <div class="kitchen_host_photo">
          <%= user_photo_tag(kitchen.user, :height => 100, :width => 100) %>
        </div>

        <ul class="kitchen_description">
          <li class="kitchen_name">
            <%= link_to kitchen.name, kitchen_path(kitchen) %>
          </li>
          <li class="kitchen_host">
            Host - <%= kitchen.user.first_name %>
          </li>
          <li class="kitchen_location">
            <%= render :partial => "kitchens/kitchen_address_no_street", :locals => { :kitchen => kitchen } %>
          </li>
        </ul>
      </div>
    </li>
  <% end %>
</ul>

app/views/kitchens/_new_kitchen_form.html.erb
<%= form_for kitchen do |f| %>

  <% if kitchen.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(kitchen.errors.count, "error") %>Please check your input for the following guideline</h2>

      <ul>
        <% kitchen.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="create_kitchen_table", cellspaceing="30">
    <tr>
      <td class="kitchen-form-label">Name</td> 
      <td><%= f.text_field :name, :class => "input_box_normal", :placeholder => "Give me a name" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">Menu</td> 
      <td><%= f.text_area :menu, :class => "text_box", :placeholder => "What's on the menu" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">Street address</td>
      <td><%= f.text_field :street_address, :class => "input_box_normal" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">City</td> 
      <td><%= f.select :city, options_for_select(Kitchen::VALID_CITIES), :class => "selection_dropdown" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">State</td> 
      <td><%= f.select :state, options_for_select(Kitchen::VALID_STATES), :class => "selection_dropdown" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">Zipcode</td> 
      <td><%= f.text_field :zipcode, :class => "input_box_normal" %></td>
    </tr>
    <tr>
      <td class="kitchen-form-label">Description</td> 
      <td><%= f.text_area :description, :placeholder => "When am I usually available to cook? What do I want in return for sharing my delicious cuisine?", :class => "text_box" %></td>
    </tr>
  </table><br>
      <%= f.submit "Submit Kitchen", :class => "button_normal" %>
<% end %>

app/views/kitchens/edit.html.erb
<div class="edit_kitchen_page">
  <div class="center_form">
    <h2>Edit my own kitchen</h2>
    
    <% if @kitchen.photos.any? %>
      <h3><%= link_to 'Edit Photos', kitchen_photos_path(@kitchen) %></h3>
    <% end %>

    <div class="kitchen_form">
      <%= render partial: "new_kitchen_form", :locals => { :kitchen => @kitchen } %>
    </div>
  </div>
  
  <div class="delete_button">
    <%= button_to("Delete Kitchen", kitchen_path(@kitchen), :method => :delete, :class => "button_normal")%>
  </div>
</div>

app/views/kitchens/index.html.erb
<div class="index_page">
  <div class="kitchen_index_cover_image">
  </div>

  <div class="index_page_intro">
    <h2>Discover Kitchens in San Francisco Bay Area</h2>
  </div>

  <div class="index_page_body">
    <%= render 'kitchens/kitchen_list', :kitchens => @kitchens %>
  </div>
</div>

app/views/kitchens/kitchen_reservations_approved.erb
<div class="reservations_list clearfix">
  <div class="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <% if @reservations.empty? %>
    There is nothing here.
  <% end %>

  <h2>Approved reservations for <%= @kitchen.name %></h2>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
  <li>
  <div class="single_reservation clearfix">
      <dl class="single_reservation_info">
        <dt class="title">Status:</dt>
        <dd><%= reservation.status %></dd>
        <dt class="title">Guest nickname:</dd>
        <dd><%= reservation.user.nickname %></dd>
        <dt class="title">Guest email:</dd>
        <dd><%= reservation.user.email %></dd>
        <dt class="title">Number of people:</dt>
        <dd><%= reservation.guest_number %></dd>
        <dt class="title">Reserve on:</dt>
        <dd><%= show_reservation_time(reservation) %></dd>
        <dt class="title">Location:</dt>
        <dd><%= kitchen_location(reservation.kitchen) %></dd>
        <dt class="title">Message from <%= reservation.user.nickname %>:</dt>
        <dd><%= reservation.message_from_guest %></dd>
        <dt class="title">My welcome message:</dt>
        <dd><%= reservation.message_from_host %></dd>
      </dl>
  </div>
  </li>
  <% end %>
  </ul>
</div>

app/views/kitchens/kitchen_reservations_approved.html.erb
<div class="reservations_list clearfix">

  <div class="title">
    <h2>Approved reservations for <%= @kitchen.name %></h2>
    <% if @reservations.empty? %>
      <h2>There is nothing here.</h2>
    <% end %>
  </div>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <ul class="description_list">
            <li class="title">Status: <%= reservation.status %></li>
            <li><%= show_reservation_time(reservation) %></li>
            <li class="guest_number"><%= reservation.guest_number %> Guest (s)</li>
            <li>
              <div class="guest_info">
                <div class="info">
                  <span class="name"><%= reservation.user.first_name %></span><span class="email"><%= reservation.user.email %></span>
                </div>
                <div class="images">
                  <span class="reservation_user_image"><%= link_to user_photo_tag(reservation.user, :type => "square", :height => 200, :width => 200), reservation.user.link, :target => "_blank" %></span>
                </div>
              </div>
            </li>
            <li><%= reservation.message_from_guest %></li>
            <li class="title">My Message to <%= reservation.user.first_name %></li>
            <li><%= reservation.message_from_host %></li>
          </ul>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/kitchens/kitchen_reservations_denied.erb
<div class="reservations_list clearfix">
  <div class="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <% if @reservations.empty? %>
    There is nothing here.
  <% end %>

  <h2>Denied reservations for <%= @kitchen.name %></h2>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
  <li>
  <div class="single_reservation clearfix">
      <dl class="single_reservation_info">
        <dt class="title">Status:</dt>
        <dd><%= reservation.status %></dd>
        <dt class="title">Guest nickname:</dd>
        <dd><%= reservation.user.nickname %></dd>
        <dt class="title">Guest email:</dd>
        <dd><%= reservation.user.email %></dd>
        <dt class="title">Number of people:</dt>
        <dd><%= reservation.guest_number %></dd>
        <dt class="title">Reserve on:</dt>
        <dd><%= show_reservation_time(reservation) %></dd>
        <dt class="title">Location:</dt>
        <dd><%= kitchen_location(reservation.kitchen) %></dd>
        <dt class="title">Message from <%= reservation.user.nickname %>:</dt>
        <dd><%= reservation.message_from_guest %></dd>
        <dt class="title">I cannot accommodate because:</dt>
        <dd><%= reservation.message_from_host %></dd>
      </dl>
  </div>
  </li>
  <% end %>
  </ul>
</div>

app/views/kitchens/kitchen_reservations_denied.html.erb
<div class="reservations_list clearfix">

  <div class="title">
    <h2>Denied reservations for <%= @kitchen.name %></h2>
    <% if @reservations.empty? %>
      <h2>There is nothing here.</h2>
    <% end %>
  </div>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <ul class="description_list">
            <li class="title">Status: <%= reservation.status %></li>
            <li><%= show_reservation_time(reservation) %></li>
            <li class="guest_number"><%= reservation.guest_number %> Guest (s)</li>
            <li>
              <div class="guest_info">
                <div class="info">
                  <span class="name"><%= reservation.user.first_name %></span><span class="email"><%= reservation.user.email %></span>
                </div>
                <div class="images">
                  <span class="reservation_user_image"><%= link_to user_photo_tag(reservation.user, :type => "square", :height => 200, :width => 200), reservation.user.link, :target => "_blank" %></span>
                </div>
              </div>
            </li>
            <li><%= reservation.message_from_guest %></li>
            <li class="title">My Message to <%= reservation.user.first_name %></li>
            <li><%= reservation.message_from_host %></li>
          </ul>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/kitchens/kitchen_reservations_pending.html.erb
<div class="reservations_list clearfix">

  <div class="user_page_notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <div class="title">
    <h2>Pending reservations for <%= @kitchen.name %></h2>
    <% if @reservations.empty? %>
      <h2>There is nothing here.</h2>
    <% end %>
  </div>

  <ul class="kitchen_reservations_list clearfix">
  <% @reservations.each do |reservation| %>
    <li class="clearfix">
      <div class="single_reservation clearfix">
          <ul class="description_list">
            <li class="title">Status: <%= reservation.status %></li>
            <li><%= show_reservation_time(reservation) %></li>
            <li class="guest_number"><%= reservation.guest_number %> Guest (s)</li>
            <li>
              <div class="guest_info">
                <div class="info">
                  <span class="name"><%= reservation.user.first_name %></span><span class="email"><%= reservation.user.email %></span>
                </div>
                <div class="images">
                  <span class="reservation_user_image"><%= link_to user_photo_tag(reservation.user, :type => "square", :height => 200, :width => 200), reservation.user.link, :target => "_blank" %></span>
                </div>
              </div>
            </li>
            <li><%= reservation.message_from_guest %></li>
            <% if reservation.in_future? %>
              <li>
                <div class="reservation_approval_form">
                  <%= render partial: "approve_reservation_form", :locals => { :reservation => reservation } %>

                  <%= render partial: "deny_reservation_form", :locals => { :reservation => reservation } %>
                </div>
              </li>
            <% else %>
              <li class="cannot_respond_explain">
                This reservation is past response time. Please respond to reservations one day prior to the reserve date.
              </li>
            <% end %>
          </ul>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/kitchens/new.html.erb
<div class="new_kitchen">
  <div class="step_explanation">
    <h2 class="step">Step 1 of 2</h2>
    <p>Create my own kitchen</p>
    <p class="explanation">Enter Kitchen description (all fields required)</p>
  </div>
  
  <div class="new_kitchen_form">
    <%= render partial: "new_kitchen_form", locals: { :kitchen => @kitchen } %>
  </div>

</div>

app/views/kitchens/pending_kitchen_reservations.erb
<div class="reservations_list">
  <div class="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <% if @reservations.empty? %>
    There is nothing here.
  <% end %>
 
  <ul>
  <% @reservations.each do |reservation| %>
    <li>
    <hr>
      <strong>Status: </strong> <%= reservation.status %><br>
      <strong>Reservation for: </strong> <%= reservation.kitchen.name %><br>
      <strong>Number of people: </strong> <%= reservation.guest_number %><br>
      <strong>Reserve on: </strong> <%= reservation.reserve_date %>, <%= show_reservation_time(reservation) %><br>
      <strong>Location: </strong> <%= reservation.kitchen.city %>, <%= reservation.kitchen.state %>, 
      							  <%= reservation.kitchen.zipcode %><br>
      <strong>Message to owner: </strong> <%= reservation.message %><br>
      <%= button_to("Approve", reservation_path(reservation), :method => :patch,
      :params => { "reservation[status]" => "approved" }, :class => "post_button")%>
      <%= button_to("Deny",    reservation_path(reservation), :method => :patch,
      :params => { "reservation[status]" => "denied" }, :class => "post_button")%>
    <hr>
    </li>
  <% end %>
  </ul>
</div>